export const pL_ver = "1.0";

export const minPerfFactor = [[0, 0, 2000], [0.17, 2000, 3000], [0.2, 3000, 3600], [0.23, 3600, 3800], [0.26, 3800, 4200], [0.29, 4200, 10000]];

export let pumpList = {
    whatsNew: "<p>Список насосов обновлён до версии "+pL_ver+".</p><p>Насосы и насосные станции представлены на некоммерческой основе исходя из рекомендаций и отзывов бурильщиков Ассоциации Объединённых Абиссинщиков</p><br><p>Добавлены следующие модели насосов:</p><p>Gidrox JET602P, Aquastrong EAJm45, Leo AJm-75, Aquastrong EKJ-802SA, Leo EKJ-802IA, Sterwins 900 WT 24-4, FGP400J, Aquastrong EAJm90H, Aquastrong EKJ-1002PA, Aquastrong EKJ-1002SA, Gidrox PKJ-1202IA, Aquastrong Aqua SMART 2-42Z, Acquaer RGJ-602S, Aquastrong EKJ-802S, Aquastrong EAJm75, Gidrox PKJ-1002SA, Aquastrong EAJm90, Aquastrong EKJ-802PA, Gidrox JET1002 Inox, Aquastrong EKJ-1202IA, Leo EKJ-802PA, Aquastrong EKJ-602I, Aquastrong EKJ-1002P, Aquastrong EAJm75H, Aquastrong EKJ-602IA, Aquastrong EKJ-1202SA, Leo EKJ-802SA, Aquario AJC-60С, Aquario AJC-110С, Gidrox JET1002P, Leo AJm-90, Jemix SGJ-100, Acquaer RGJ-1002P, P.I.T. POG370-P1, Leo EKJ-602I, Aquastrong EKJ-1002S, Gidrox PKJ-1202PА, Gidrox JET802P, Gidrox PKJ-1202SA, Gidrox PKJ-1002PА, Aquastrong EKJ-602PA, Leo EKJ-1002I, Leo EKJ-1002S, Leo EKJ-1002IA, Gidrox PKJ-1002IA, Сармат WZBS-35, Gidrox PKJ-802SA, Aquastrong EKJ-802P, Джилекс Джамбо 70/50 П (2.0), Leo EKJ-1202S, Leo EKJ-802S, Aquastrong EKJ-602S, Leo EKJ-802I, Ресанта ПСН-3600П, Leo EKJ-1002PA, Leo EKJ-1002P, Aquastrong EKJ-802IA, Aquastrong EKJ-1202PA, Aquastrong EKJ-1002I, Leo EKJ-1002SA, Aquario AJC-61С, Gidrox PKJ-602PА, Aquastrong EKJ-1202S, Gidrox PKJ-802IA, Aquastrong EKJ-1002IA, Джилекс Джамбо 70/50 Ч (2.0), Leo EKJ-1202IA, Aquastrong EKJ-1202I, Aquastrong EAJm60, Acquaer RGJ-602I, Leo AJm-60, Aquastrong EKJ-1202P, Leo EKJ-602P, Sterwins 900 JET-3, Leo EKJ-1202SA, Verton AQUA APS500MS, Leo EKJ-602PA, Aquastrong EKJ-802I, Leo EKJ-1202I, Leo EKJ-602SA, Leo EKJ-602IA, Aquor 1AWZB750, Gidrox PKJ-802PА, Leo EKJ-802P, Aquastrong EKJ-602P, Leo EKJ-1202PA, Gidrox JET800 Inox, Leo EKJ-1202P, Leo EKJ-602S, Aquastrong EKJ-602P, Aquastrong EAJm150H.</p>",
    models: [
        {
            name: "Sterwins 900 JET-3",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 900,
            maxPerfLPM: null,
            maxPerfLPH: 3800,
            liftingHeight: 43,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Sterwins 900 WT 24-4",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 900,
            maxPerfLPM: null,
            maxPerfLPH: 3800,
            liftingHeight: 43,
            forLowStaticLevel: true,
            accumulator: "24",
        },
        {
            name: "Aquastrong EKJ-602PA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Aquastrong EKJ-802PA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 800,
            maxPerfLPM: 62,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Aquastrong EKJ-1002PA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 1000,
            maxPerfLPM: 75,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Aquastrong EKJ-1202PA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 1200,
            maxPerfLPM: 83,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Aquastrong EKJ-602IA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Aquastrong EKJ-802IA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 800,
            maxPerfLPM: 62,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Aquastrong EKJ-1002IA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 1000,
            maxPerfLPM: 75,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Aquastrong EKJ-1202IA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 1200,
            maxPerfLPM: 84,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Aquastrong EKJ-802SA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 800,
            maxPerfLPM: 62,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Aquastrong EKJ-1002SA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 1000,
            maxPerfLPM: 75,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Aquastrong EKJ-1202SA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 1200,
            maxPerfLPM: 83,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Aquastrong EKJ-602P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-602P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-802P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 800,
            maxPerfLPM: 62,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-1002P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 1000,
            maxPerfLPM: 75,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-1202P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 1200,
            maxPerfLPM: 83,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-602S",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-802S",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 800,
            maxPerfLPM: 62,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-1002S",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 1000,
            maxPerfLPM: 75,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-1202S",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 1200,
            maxPerfLPM: 83,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-602I",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-802I",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 800,
            maxPerfLPM: 62,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-1002I",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 1000,
            maxPerfLPM: 75,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EKJ-1202I",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 1200,
            maxPerfLPM: 83,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EAJm75H",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 750,
            maxPerfLPM: 47,
            maxPerfLPH: null,
            liftingHeight: 51,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EAJm75",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 750,
            maxPerfLPM: 65,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EAJm60",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 600,
            maxPerfLPM: 47,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EAJm45",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 450,
            maxPerfLPM: 35,
            maxPerfLPH: null,
            liftingHeight: 41,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EAJm90H",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 900,
            maxPerfLPM: 47,
            maxPerfLPH: null,
            liftingHeight: 62,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EAJm90",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 900,
            maxPerfLPM: 65,
            maxPerfLPH: null,
            liftingHeight: 48,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong EAJm150H",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 1500,
            maxPerfLPM: 70,
            maxPerfLPH: null,
            liftingHeight: 72,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Gidrox PKJ-602PА",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Gidrox PKJ-802PА",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 800,
            maxPerfLPM: 60,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Gidrox PKJ-1002PА",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 1000,
            maxPerfLPM: 60,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Gidrox PKJ-1202PА",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 1200,
            maxPerfLPM: 77,
            maxPerfLPH: null,
            liftingHeight: 46,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Gidrox PKJ-802IA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 800,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 38,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Gidrox PKJ-1002IA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 1000,
            maxPerfLPM: 77,
            maxPerfLPH: null,
            liftingHeight: 46,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Gidrox PKJ-1202IA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 1200,
            maxPerfLPM: 83,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Gidrox PKJ-802SA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 800,
            maxPerfLPM: 60,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Gidrox PKJ-1002SA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 1000,
            maxPerfLPM: 77,
            maxPerfLPH: null,
            liftingHeight: 46,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Gidrox PKJ-1202SA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 1200,
            maxPerfLPM: 77,
            maxPerfLPH: null,
            liftingHeight: 46,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Gidrox JET602P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Gidrox JET802P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 800,
            maxPerfLPM: 55,
            maxPerfLPH: null,
            liftingHeight: 38,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Gidrox JET1002P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 1000,
            maxPerfLPM: 75,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Gidrox JET800 Inox",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 800,
            maxPerfLPM: 60,
            maxPerfLPH: null,
            liftingHeight: 38,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Gidrox JET1002 Inox",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 1000,
            maxPerfLPM: 75,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-602PA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-802PA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 800,
            maxPerfLPM: 58,
            maxPerfLPH: null,
            liftingHeight: 38,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-1002PA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 1000,
            maxPerfLPM: 73,
            maxPerfLPH: null,
            liftingHeight: 44,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-1202PA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Пластик",
            capacity: 1200,
            maxPerfLPM: 80,
            maxPerfLPH: null,
            liftingHeight: 48,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-602SA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-802SA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 800,
            maxPerfLPM: 58,
            maxPerfLPH: null,
            liftingHeight: 38,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-1002SA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 1000,
            maxPerfLPM: 73,
            maxPerfLPH: null,
            liftingHeight: 44,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-1202SA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 1200,
            maxPerfLPM: 80,
            maxPerfLPH: null,
            liftingHeight: 48,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-602IA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-802IA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 800,
            maxPerfLPM: 58,
            maxPerfLPH: null,
            liftingHeight: 38,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-1002IA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 1000,
            maxPerfLPM: 73,
            maxPerfLPH: null,
            liftingHeight: 44,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-1202IA",
            pumpType: "Центробежный",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 1200,
            maxPerfLPM: 80,
            maxPerfLPH: null,
            liftingHeight: 48,
            forLowStaticLevel: true,
            accumulator: "19",
        },
        {
            name: "Leo EKJ-602P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-802P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 800,
            maxPerfLPM: 62,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-1002P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 1000,
            maxPerfLPM: 73,
            maxPerfLPH: null,
            liftingHeight: 44,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-1202P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 1200,
            maxPerfLPM: 83,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-602I",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-802I",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 800,
            maxPerfLPM: 62,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-1002I",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 1000,
            maxPerfLPM: 73,
            maxPerfLPH: null,
            liftingHeight: 44,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-1202I",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 1200,
            maxPerfLPM: 83,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-602S",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-802S",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 800,
            maxPerfLPM: 62,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-1002S",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 1000,
            maxPerfLPM: 75,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo EKJ-1202S",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 1200,
            maxPerfLPM: 83,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo AJm-60",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 600,
            maxPerfLPM: 47,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo AJm-75",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 750,
            maxPerfLPM: 65,
            maxPerfLPH: null,
            liftingHeight: 40,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Leo AJm-90",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 900,
            maxPerfLPM: 65,
            maxPerfLPH: null,
            liftingHeight: 48,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Acquaer RGJ-1002P",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 1000,
            maxPerfLPM: 70,
            maxPerfLPH: null,
            liftingHeight: 44,
            forLowStaticLevel: false,
            accumulator: "Нет",
        },
        {
            name: "Acquaer RGJ-602S",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: false,
            accumulator: "Нет",
        },
        {
            name: "Acquaer RGJ-602I",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 600,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 35,
            forLowStaticLevel: false,
            accumulator: "Нет",
        },
        {
            name: "Ресанта ПСН-3600П",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 900,
            maxPerfLPM: 60,
            maxPerfLPH: null,
            liftingHeight: 45,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Джилекс Джамбо 70/50 П (2.0)",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 1100,
            maxPerfLPM: 70,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Джилекс Джамбо 70/50 Ч (2.0)",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 1100,
            maxPerfLPM: 70,
            maxPerfLPH: null,
            liftingHeight: 50,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquario AJC-60С",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 550,
            maxPerfLPM: 40,
            maxPerfLPH: null,
            liftingHeight: 38,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquario AJC-61С",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 600,
            maxPerfLPM: 47,
            maxPerfLPH: null,
            liftingHeight: 39,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "Aquario AJC-110С",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Чугун",
            capacity: 1100,
            maxPerfLPM: 70,
            maxPerfLPH: null,
            liftingHeight: 43,
            forLowStaticLevel: true,
            accumulator: "Нет",
        },
        {
            name: "FGP400J",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Пластик",
            capacity: 400,
            maxPerfLPM: null,
            maxPerfLPH: 2600,
            liftingHeight: 30,
            forLowStaticLevel: false,
            accumulator: "Нет",
        },
        {
            name: "Jemix SGJ-100",
            pumpType: "Центробежный",
            pumpControl: "Нет",
            bodyMaterial: "Нержавеющая сталь",
            capacity: 750,
            maxPerfLPM: 60,
            maxPerfLPH: null,
            liftingHeight: 42,
            forLowStaticLevel: false,
            accumulator: "Нет",
        },
        {
            name: "Aquastrong Aqua SMART 2-42Z",
            pumpType: "Центробежный",
            pumpControl: "Частотное",
            bodyMaterial: "Пластик",
            capacity: 550,
            maxPerfLPM: null,
            maxPerfLPH: 4500,
            liftingHeight: 45,
            forLowStaticLevel: false,
            accumulator: "0,2",
            pumpPoints:{
                minPerfLPH: 2000, // обязательно для "умных" насосов
            }
        },
        {
            name: "P.I.T. POG370-P1",
            pumpType: "Вихревой",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 370,
            maxPerfLPM: 33,
            maxPerfLPH: null,
            liftingHeight: 30,
            forLowStaticLevel: false,
            accumulator: "2",
        },
        {
            name: "Verton AQUA APS500MS",
            pumpType: "Вихревой",
            pumpControl: "Частотное",
            bodyMaterial: "Чугун",
            capacity: 500,
            maxPerfLPM: 50,
            maxPerfLPH: null,
            liftingHeight: 38,
            forLowStaticLevel: false,
            accumulator: "2",
        },
        {
            name: "Aquor 1AWZB750",
            pumpType: "Вихревой",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 750,
            maxPerfLPM: 42,
            maxPerfLPH: null,
            liftingHeight: 42,
            forLowStaticLevel: false,
            accumulator: "1",
        },
        {
            name: "Сармат WZBS-35",
            pumpType: "Вихревой",
            pumpControl: "Релейное",
            bodyMaterial: "Чугун",
            capacity: 370,
            maxPerfLPM: 30,
            maxPerfLPH: null,
            liftingHeight: 32,
            forLowStaticLevel: false,
            accumulator: "2",
        },
    ],
};
