const version = "1.0.1";

export const mainStr = {
    "infoHeader": "О программе",
    "infoText": "DrillMate SPA версия "+version+"<br><a href='https://github.com/R3DRUMVNE/DrillMate/' target='_blank'>GitHub</a> | <a href='https://t.me/r3drumvne/' target='_blank'>Обратная связь</a><br><br>Создано для Ассоциации Объединённых Абиссинщиков<br>От людей для людей<br><br>Лицензия <a href='./LICENSE.txt' target='_blank'>CC-BY-SA-4.0</a><br>© П.С. Симолкин, 2025",
    "bugButton": "Сообщить об ошибке",
    "downloadButton": "Загрузить на устройство",
    "closeButton": "Закрыть",
    "bugReportHeader": "Сообщить об ошибке",
    "bugReportInfo": "Вы можете сообщить об ошибке, написав разработчику через обратную связь и описав проблему. Пожалуйста, скопируйте и приложите к описанию проблемы информацию, расположенную ниже. Данная информация о клиенте не собирается и не хранится где-либо - получить её разработчик может только от вас",
    "copyButton": "Скопировать и отправить",
};

export const blockInfoStrings = {
    "schetovod": "Как пользоваться:<br>1. Возьмите ёмкость с известным объёмом.<br>2. Впишите объём заполняемой ёмкости.<br>3. Одновременно нажмите \"Старт\" и начните заполнять ёмкость водой из скважины.<br>4. Как только ёмкость будет заполнена нажмите \"Стоп!\".<br>5. Готово!",
    "daicamlock": "Условный проход DN выбирается по камлокам типа \"E\" и \"C\" с учётом заужения за счёт штуцера под шланг и отличается от DN, указанного производителем. Если требуется собрать соединения из камлоков без штуцера - ориентируйтесь по размерам \"P\", \"E\" и \"K\"",
    "tehpas": "1. Поля заполнять необязательно. Их можно заполнить от руки после печати.<br>2. Снимите отметки с пунктов, которые не нужно отображать в паспорте.<br>3. При печати выключите отображение колонтитулов, если они вам не нужны.<br>4. Размеры для шапки техпаспорта: ширина - 900px, высота - не более 150px."
}

export const schetovodStr = {
    "realtimeText": "Расчёт в реальном времени",
    "volumeText": "Заполняемый объём, литр:",
    "userTimeText": "Время заполнения, час:мин:сек:",
    "startButton": "Старт!",
    "currentTimeText": "Время",
    "currentTimeOutput": "-",
    "flowRateText": "Дебит",
    "flowRateLMOutput": "-",
    "flowRateLHOutput": "-",
    volumeInputHint: "0",
};

export const daicamlockStr = {
    "answerContainer": "Ваш камлок: ",
    "fatherLabel": "Папа",
    "motherLabel": "Мама",
    "hoseFittingLabel": "Штуцер под шланг",
    "internalThreadLabel": "Внутренняя резьба",
    "externalThreadLabel": "Внешняя резьба",
    "stubLabel": "Заглушка",
    "DNSelectLabel": "DN, мм | дюйм:",
    "sizesBlockHeader": "Размеры на эскизе",
    "sizeLabel1": "-",
    "sizeLabel2": "-",
    "sizeLabel3": "-",
};

export const tehpasStr = {
    "headerUploadLabel": "Установить шапку",
    "openFileLabel": "Открыть",
    "saveFileButton": "Сохранить",
    "fileSaveHeader": "Сохранить техпаспорт в файл",
    "fileNameLabel": "Введите имя файла:",
    "fileNameHint": "Техпаспорт_скважины",
    "generalInfoHeader": "Общая информация",
    "passNumberLabel": "Номер техпаспорта:",
    "passNumberHint": "123",
    "wellLocationLabel": "Местоположение скважины:",
    "wellLocationHint": "Адрес",
    "drillMasterLabel": "Буровой мастер:",
    "drillMasterHint": "Фамилия Имя Отчество",
    "drillMasterContactsLabel": "Контакты:",
    "drillMasterContactsHint": "Телефон и др.",
    "customerLabel": "Заказчик:",
    "customerHint": "Фамилия Имя Отчество",
    "customerContactsLabel": "Контакты:",
    "customerContactsHint": "Телефон и др.",
    "startWorkLabel": "Начало работ:",
    "endWorkLabel": "Окончание работ:",
    "wellParamsHeader": "Параметры скважины",
    "wellTypeLabel": "Вид скважины:",
    "wellTypeSelect": [["Абиссинская скважина", "Абиссинская забивная скважина \"Игла\"", "Абиссинский \"колодец\"", "Скважина на песок под погружной насос"],
                        ["abyss", "abyssNeedle", "abyssSump", "wellSubmersiblePump"]],
    "pipesUsedLabel": "Применяемые трубы:",
    "pipesUsedHint": "ПНД 32мм ГОСТ 18599-2001",
    "wellDepthLabel": "Глубина скважины, м:",
    "wellDepthHint": "0",
    "appliedFilterLabel": "Применяемый фильтр:",
    "appliedFilterHint": "ПВД",
    "filterLengthLabel": "Длина фильтра, м:",
    "filterLengthHint": "0",
    "staticLevelLabel": "Статический уровень, м:",
    "staticLevelHint": "0",
    "dynamicLevelLabel": "Динамический уровень, м:",
    "dynamicLevelHint": "0",
    "flowRateLabel": "Дебит скважины, л/ч:",
    "flowRateHint": "1000",
    "wbHeader": "Гарантийные обязательства",
    "wbHint": "Текст",
    "rbHeader": "Рекомендации по эксплуатации скважины",
    "pumpLabel": "Насосное оборудование:",
    "pumpHint": "Рекомендуемое и/или нежелательное насосное оборудование для скважины",
    "extraRecommendLabel": "Доп. рекомендации:",
    "extraRecommendHint": "Текст",

    "gsShowLabel": "Отображать раздел",
    "gsDrawSLLabel": "Статический уровень",
    "geoSectionHeader": "Геологический разрез в месте бурения",
    "depthLabel": "Глубина от поверхности, м",
    "startDepthLabel": "от:",
    "startDepthHint": "0",
    "endDepthLabel": "до:",
    "endDepthHint": "0",
    "layerNameLabel": "Слой:",
    "layerNameSelect": ["Почва", "Торф", "Глина", "Суглинок", "Супесь пылеватая", "Супесь песчаная", "Песок мелкой фракции", "Песок средней фракции", "Песок крупной фракции", "Песчано-гравийная смесь", "Гравий"],
    "layerColorLabel": "Цвет:",
    "layerColorSelect": [["Коричневый цвет", "Тёмно-коричневый цвет", "Рыжий цвет", "Жёлтый цвет", "Белый цвет", "Голубой цвет", "Серый цвет", "Тёмно-серый цвет", "Чёрный цвет"],
                        ["Chocolate", "SaddleBrown", "IndianRed", "Khaki", "White", "DarkTurquoise", "Silver", "Gray", "#4d4d4d"]],
    "wellConstructionLabel": "Конструкция скважины",
    "wellConstructionSelect": [["Нет", "Водозаборная труба", "Фильтровая зона", "Водозаборная и обсадная труба", "Погружной насос и обсадная труба", "Погружной насос и фильтровая зона", "Водозаборная труба и фильтровая зона на обсадной трубе", "Фильтровая зона на обсадной трубе", "Обсадная труба"],
                            ["nothing", "waterIntakePipe", "filterZone", "waterIntakePipeCasing", "submersiblePumpCasing", "submersiblePumpFilterZone", "filterZoneWaterIntakePipeCasing", "filterZoneCasing", "casing"]],
    "addLayerButton": "Добавить слой",
    "removeLayerButton": "Удалить слой",

    "dsPrintLabel": "Двухсторонняя печать",
    "signaturesPrintLabel": "Блок подписей",
    "formPassButton": "Сформировать паспорт!",

    "passportHeaderLabel": "Технический паспорт",
    "passportUnderHeaderLabel": "водозаборной скважины для хозяйственного водоснабжения",
    "gsTableHeader": ["Глубина, м", "Порода, цвет", "Конструкция скважины"],

    "signaturesTableHeader": "Подписи сторон",
    "jobDone": "<b>Работу сдал:</b>",
    "acceptJob": "<b>Работу принял:</b>",
    "signatureField": "________",
    "transcriptField": "______________________",
    "dateField": "<___> _________ 20___г.",
};