const version = "1.1.0";

export const mainStr = {
    "settingsInfoHeader": "Настройки и информация",
    "infoText": "DrillMate SPA версия "+version+"<br><a href='https://github.com/R3DRUMVNE/DrillMate/' target='_blank'>GitHub</a> | <a href='https://t.me/r3drumvne/' target='_blank'>Обратная связь</a><br><br>Веб-приложение разработано на некоммерческой основе специально для Ассоциации Объединённых Абиссинщиков, не собирает и не передаёт третьим лицам какую-либо информацию, вводимую пользователем.<br><br>Лицензия <a href='./LICENSE.txt' target='_blank'>CC-BY-SA-4.0</a><br>© П.С. Симолкин, 2025",
    "themeSelectLabel": "Тема веб-приложения:",
    "themeSelect": [["Как в системе", "likeSystem"], ["Стандартная", "default"], ["Тёмная", "dark"], ["Серая", "gray"]],
    "bugButton": "Сообщить об ошибке",
    "downloadButton": "Загрузить на устройство",
    "closeButton": "Закрыть",
    "bugReportHeader": "Сообщить об ошибке",
    "bugReportInfo": "Вы можете сообщить об ошибке, написав разработчику через обратную связь и описав проблему. Пожалуйста, скопируйте и приложите к описанию проблемы информацию, расположенную ниже. Данная информация о клиенте не собирается и не хранится где-либо - получить её разработчик может только от вас",
    "copyButton": "Скопировать и отправить",
};

export const blockInfoStrings = {
    "schetovod": "<p>Как пользоваться:</p><p>1. Возьмите ёмкость с известным объёмом.</p><p>2. Впишите объём заполняемой ёмкости.</p><p>3. Одновременно нажмите \"Старт\" и начните заполнять ёмкость водой из скважины.</p><p>4. Как только ёмкость будет заполнена нажмите \"Стоп!\".</p><p>5. Готово!</p>",
    "daicamlock": "Условный проход DN выбирается по камлокам типа \"E\" и \"C\" с учётом заужения за счёт штуцера под шланг и отличается от DN, указанного производителем. Если требуется собрать соединения из камлоков без штуцера - ориентируйтесь по размерам \"P\", \"E\" и \"K\"",
    "tehpas": "<p>1. Поля заполнять необязательно. Их можно заполнить от руки после печати.</p><p>2. Снимите отметки с блоков и пунктов, которые не нужно отображать в паспорте.</p><p>3. При печати выключите отображение колонтитулов, если они вам не нужны.</p><p>4. Размеры для шапки техпаспорта: ширина - 900px, высота - не более 150px.</p>",
    "prokachaika": "<p>1. В данном разделе представлен список самовсасывающих поверхностных насосов для абиссинских скважин.</p><p>2. При необходимости заполните интересующие вас фильтры и список автоматически подстроится под них.</p><p>3. При вводе дебита скважины расчитываются баллы для насосов через отношение дебита скважины к макс. производительности, за исключением насосов с частотным регулированием. Насосы, чья макс. производительность меньше, чем введённый дебит, будут скрыты из списка. Отдавайте приоритет насосам с большим баллом, но учитывайте статику в скважине и необходимое давление в системе.<br>Значение \"ИЗБ\" означает, что насос может работать на скважине, однако его макс. производительность избыточна для вашего дебита, что может привести к увеличенному шуму насоса, а также, в некоторых случаях, излишней кавитации или просадке динамики (неравномерному напору, плевкам).</p>",
}

export const schetovodStr = {
    "realtimeText": "Расчёт в реальном времени",
    "volumeText": "Заполняемый объём, литр:",
    "userTimeText": "Время заполнения, час:мин:сек:",
    "startButton": "Старт!",
    "currentTimeText": "Время",
    "currentTimeOutput": "-",
    "flowRateText": "Дебит",
    "flowRateLMOutput": "-",
    "flowRateLHOutput": "-",
    volumeInputHint: "0",
};

export const daicamlockStr = {
    "answerContainer": "Ваш камлок: ",
    "fatherLabel": "Папа",
    "motherLabel": "Мама",
    "hoseFittingLabel": "Штуцер под шланг",
    "internalThreadLabel": "Внутренняя резьба",
    "externalThreadLabel": "Внешняя резьба",
    "stubLabel": "Заглушка",
    "DNSelectLabel": "DN, мм | дюйм:",
    "DNSelect": ["10мм | 3/8\"", "15мм | 1/2\"", "20мм | 3/4\"", "25мм | 1\"", "32мм | 1-1/4\"", "40мм | 1-1/2\"", "50мм | 2\"", "65мм | 2-1/2\"", "80мм | 3\"", "100мм | 4\"", "125мм | 5\""],
    "sizesBlockHeader": "Размеры на эскизе",
    "sizeLabel1": "-",
    "sizeLabel2": "-",
    "sizeLabel3": "-",
    "getCamlockHeader": "Найти в продаже",
};

export const tehpasStr = {
    "headerUploadLabel": "Установить шапку",
    "openFileLabel": "Открыть",
    "saveFileButton": "Сохранить",
    "fileSaveHeader": "Сохранить техпаспорт в файл",
    "fileNameLabel": "Введите имя файла:",
    "fileNameHint": "Техпаспорт_скважины",
    "toNextPageCheckboxLabel": "Блок с новой страницы",
    "generalInfoHeader": "Общая информация",
    "passNumberLabel": "Номер техпаспорта:",
    "passNumberHint": "123",
    "wellLocationLabel": "Местоположение скважины:",
    "wellLocationHint": "Адрес",
    "drillMasterLabel": "Буровой мастер:",
    "drillMasterHint": "Фамилия Имя Отчество",
    "drillMasterContactsLabel": "Контакты:",
    "drillMasterContactsHint": "Телефон и др.",
    "customerLabel": "Заказчик:",
    "customerHint": "Фамилия Имя Отчество",
    "customerContactsLabel": "Контакты:",
    "customerContactsHint": "Телефон и др.",
    "startWorkLabel": "Начало работ:",
    "endWorkLabel": "Окончание работ:",
    "wellParamsHeader": "Параметры скважины",
    "wellTypeLabel": "Вид скважины:",
    "wellType": [["Абиссинская скважина", "abyss"], ["Абиссинская забивная скважина \"Игла\"", "abyssNeedle"], ["Абиссинский \"колодец\"", "abyssSump"], ["Скважина под погружной насос", "wellSubmersiblePump"]],
    "pipesUsedLabel": "Применяемые трубы:",
    "pipesUsedHint": "ПНД 32мм ГОСТ 18599-2001",
    "wellDepthLabel": "Глубина скважины, м:",
    "wellDepthHint": "0",
    "appliedFilterLabel": "Применяемый фильтр:",
    "appliedFilterHint": "ПВД",
    "filterLengthLabel": "Длина фильтра, м:",
    "filterLengthHint": "0",
    "staticLevelLabel": "Статический уровень, м:",
    "staticLevelHint": "0",
    "dynamicLevelLabel": "Динамический уровень, м:",
    "dynamicLevelHint": "0",
    "flowRateLabel": "Дебит скважины, л/ч:",
    "flowRateHint": "1000",
    "wbHeader": "Гарантийные обязательства",
    "wbBlockCheckboxLabel": "Отображать блок",
    "wbHint": "Текст",
    "rbHeader": "Рекомендации по эксплуатации скважины",
    "pumpLabel": "Насосное оборудование:",
    "pumpHint": "Рекомендуемое и/или нежелательное насосное оборудование для скважины",
    "extraRecommendLabel": "Доп. рекомендации:",
    "extraRecommendHint": "Текст",

    "gsBlockShowLabel": "Отображать блок",
    "gsDrawSLLabel": "Статический уровень",
    "geoSectionHeader": "Геологический разрез в месте бурения",
    "depthLabel": "Глубина от поверхности, м",
    "startDepthLabel": "от:",
    "startDepthHint": "0",
    "endDepthLabel": "до:",
    "endDepthHint": "0",
    "layerNameLabel": "Слой:",
    "layerName": ["Почва", "Торф", "Глина", "Суглинок", "Супесь пылеватая", "Супесь песчаная", "Песок мелкой фракции", "Песок средней фракции", "Песок крупной фракции", "Песчано-гравийная смесь", "Гравий", "Твёрдая порода"],
    "layerColorLabel": "Цвет:",
    "layerColor": [["Коричневый цвет", "Chocolate"], ["Тёмно-коричневый цвет", "SaddleBrown"], ["Рыжий цвет", "IndianRed"], ["Жёлтый цвет", "Khaki"], ["Белый цвет", "AliceBlue"], ["Голубой цвет", "DarkTurquoise"], ["Серый цвет", "Silver"], ["Тёмно-серый цвет", "Gray"], ["Чёрный цвет", "#4d4d4d"]],
    "wellConstructionLabel": "Конструкция скважины:",
    "wellConstruction": [["Нет", "nothing"], ["Водозаборная труба", "waterIntakePipe"], ["Фильтровая зона", "filterZone"], ["Водозаборная и обсадная труба", "waterIntakePipeCasing"], ["Погружной насос и обсадная труба", "submersiblePumpCasing"], ["Погружной насос и фильтровая зона", "submersiblePumpFilterZone"], ["Водозаборная труба и фильтровая зона на обсадной трубе", "filterZoneWaterIntakePipeCasing"], ["Фильтровая зона на обсадной трубе", "filterZoneCasing"], ["Обсадная труба", "casing"]],
    "addLayerButton": "Добавить слой",
    "removeLayerButton": "Удалить слой",

    "dsPrintLabel": "Двухсторонняя печать",
    "signaturesPrintLabel": "Блок подписей",
    "formPassButton": "Сформировать паспорт!",

    "passportHeaderLabel": "Технический паспорт",
    "passportUnderHeaderLabel": "водозаборной скважины для хозяйственного водоснабжения",
    "gsTableHeader": ["Глубина, м", "Порода, цвет", "Конструкция скважины"],

    "signaturesTableHeader": "Подписи сторон",
    "jobDone": "<b>Работу сдал:</b>",
    "acceptJob": "<b>Работу принял:</b>",
    "signatureField": "________",
    "transcriptField": "______________________",
    "dateField": "<___> _________ 20___г.",
};

export const prokachaikaStr = {
    "filterBlockHeader": "Фильтры",
    "findPumpLabel": "Название модели:",
    "findPumpHint": "Sterwins 900 JET-3",
    "pumpTypeSelectLabel": "Тип насоса:",
    "pumpTypeSelect": ["Любой", "Центробежный", "Вихревой"],
    "pumpControlSelectLabel": "Управление насосом:",
    "pumpControlSelect": ["Любое", "Нет", "Релейное", "Частотное"],
    "bodyMaterialSelectLabel": "Материал корпуса:",
    "bodyMaterialSelect": ["Любой", "Пластик", "Нержавеющая сталь", "Чугун"],
    "wellFlowRateLabel": "Дебит скважины, л/ч:",
    "wellFlowRateHint": "1000",
    "pressureLabel": "Макс. давление:",
    "pressure": [["Любое", "any"], ["≤3 бар", "0-3"], ["3 ÷ 4 бар", "3-4"], [">4 бар", "4-100"]],
    "lowStaticLabel": "Статика ≤-6м",
    "hideExcessPumpLabel": "Скрывать \"ИЗБ\"",
    "filtersResetButton": "Сбросить фильтры",
    "compareButton": "Таблица сравнения",
    "cL_deleteButton": "Удалить",
    "cL_clearButton": "Очистить",
    "cL_closeButton": "Закрыть",

    "pumpTypeLabel": "Тип насоса:",
    "pumpVersionLabel": "Исполнение модели:",
    "pumpControlLabel": "Управление насосом:",
    "bodyMaterialLabel": "Материал корпуса:",
    "capacityLabel": "Макс. мощность, Вт:",
    "maxPerfLabel": "Макс. производительность:",
    "liftingHeightLabel": "Высота подъёма, м:",
    "maxPressureLabel": "Макс. давление, бар:",
    "forLowStaticLevelLabel": "Для низких статик:",
    "accumulatorLabel": "Гидроаккумулятор, л:",
    "relayHAButton": "Настройки реле-гидроаккумулятор",
    "searchPumpLabel": "Найти в продаже:",
    "shareButton": "Поделиться",
    "goComparePumpButton": "Сравнить",
    "pI_closeButton": "Закрыть",

    "rHA_header": "Рекомендуемые настройки реле-ГА",
    "pressureOnLabel": "Давление включения насоса, бар:",
    "pressureOnInput": "1,4",
    "pressureHALabel": "Давление воздуха в ГА, бар:",
    "pressureOffLabel": "Давление выключения насоса, не более, бар:",
    "rHA_closeButton": "Закрыть",
};